@base_url = http://localhost:3000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RpbmdAdGVzdC5jb20iLCJpYXQiOjE1OTcwODQ0OTR9.eyPCUexkGPJTg3TbrJf9nfeReICI4gbSkm81iTqQvGs

// Get Own Profile ID
GET {{base_url}}/auth/me HTTP/1.1
token: {{token}}
###
// Create User
POST {{base_url}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "user_name": "testing",
    "user_username": "testing0",
    "user_email": "testing@test.com",
    "user_password": "12345678",
    "user_areaPreference": "Las Palmas"
}

// User Log In
###
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "user_email": "Lito@test.com",
    "user_password": "123456"
}

###
