@base_url = http://localhost:3000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpdG9AdGVzdC5jb20iLCJpYXQiOjE1OTYxMzI4NjIsImV4cCI6MTU5ODcyNDg2Mn0.Vc0xp2xoWXj1WjeSC37Z3X160J2DTaoIgWj8VBivPT4

// Get All Events
GET {{base_url}}/events/ HTTP/1.1
###

// Get Event by ID
GET {{base_url}}/events/5f21d2623ed42dbefe2f9b72 HTTP/1.1
###

// Get Event by Tag
GET {{base_url}}/events/tags/1223 HTTP/1.1
###

// Get Event by Category
GET {{base_url}}/events/category/Sports HTTP/1.1
###

// Get Event by Search
GET {{base_url}}/events/search/Super HTTP/1.1
###

// Create Event
POST {{base_url}}/events/me HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "title": "To be deleted!",
    "description": "Surf Competition",
    "eventDate": "August 21st, 2020",
    "capacity": 220,
    "price": 25,
    "category": "Sports"
}
###

// Update Event
PUT {{base_url}}/events/me/5f22faa51205c8d5eaf89969 HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "title": "Mega Super Event"
}
###

// Add Event Saves
PUT {{base_url}}/events/me/5f22faa51205c8d5eaf89969/save HTTP/1.1
token: {{token}}
###

// Add Event Attendance
PUT {{base_url}}/events/me/5f22faa51205c8d5eaf89969/attendance HTTP/1.1
token: {{token}}
###

// Add Event Views
PUT {{base_url}}/events/me/5f21d2623ed42dbefe2f9b72/views HTTP/1.1
###

// Delete Event
DELETE {{base_url}}/events/me/5f23139e12368ada55776cec HTTP/1.1
token: {{token}}
###
