@base_url = http://localhost:3000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RpbmdAdGVzdC5jb20iLCJpYXQiOjE1OTcwODQ0OTR9.eyPCUexkGPJTg3TbrJf9nfeReICI4gbSkm81iTqQvGs

// Get Own Profile
GET {{base_url}}/users/me HTTP/1.1
token: {{token}}
###

// Get User Profile
GET {{base_url}}/users/5f21cb5409603ebc07741d55 HTTP/1.1
###

// Get Own Profile Saved Events
GET {{base_url}}/users/me/savedEvents HTTP/1.1
token: {{token}}
###

// Get Own Profile Attending Events
GET {{base_url}}/users/me/attendingEvents HTTP/1.1
token: {{token}}
###

// Edit Own Profile
PUT {{base_url}}/users/me HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "name": "Carlitos Way"
}
###

// Edit Own Photo
PUT {{base_url}}/users/me/photo HTTP/1.1
###

// Delete User Account
DELETE {{base_url}}/users/5f21cf9855fcd8be31c21d5d HTTP/1.1
###
